-- Table for Products
DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  description VARCHAR(255),
  price INTEGER NOT NULL,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  image_url VARCHAR(255),
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  is_sold BOOLEAN NOT NULL DEFAULT FALSE
);